// <auto-generated />
using System;
using AutoEatery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoEatery.Data.Migrations
{
    [DbContext(typeof(EateryDbContext))]
    partial class EateryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("AutoEatery.Data.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CookedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 1580,
                            CookedAt = new DateTime(2023, 9, 30, 9, 29, 54, 641, DateTimeKind.Local).AddTicks(8931),
                            Price = 373.746522532923100m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 1848,
                            CookedAt = new DateTime(2023, 9, 29, 16, 52, 53, 995, DateTimeKind.Local).AddTicks(8913),
                            Price = 824.205990673156600m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 819,
                            CookedAt = new DateTime(2023, 9, 29, 16, 56, 42, 178, DateTimeKind.Local).AddTicks(9760),
                            Price = 106.42144288383720100m
                        },
                        new
                        {
                            Id = 4,
                            Calories = 1296,
                            CookedAt = new DateTime(2023, 9, 29, 19, 31, 13, 772, DateTimeKind.Local).AddTicks(2195),
                            Price = 276.093057448989100m
                        },
                        new
                        {
                            Id = 5,
                            Calories = 983,
                            CookedAt = new DateTime(2023, 9, 30, 3, 10, 16, 274, DateTimeKind.Local).AddTicks(8548),
                            Price = 654.288319225168300m
                        },
                        new
                        {
                            Id = 6,
                            Calories = 1142,
                            CookedAt = new DateTime(2023, 9, 30, 3, 5, 10, 603, DateTimeKind.Local).AddTicks(6591),
                            Price = 519.094210386148300m
                        },
                        new
                        {
                            Id = 7,
                            Calories = 1946,
                            CookedAt = new DateTime(2023, 9, 30, 6, 46, 16, 974, DateTimeKind.Local).AddTicks(1595),
                            Price = 162.3966910475346100m
                        },
                        new
                        {
                            Id = 8,
                            Calories = 1100,
                            CookedAt = new DateTime(2023, 9, 30, 2, 42, 28, 619, DateTimeKind.Local).AddTicks(7579),
                            Price = 474.875851504554100m
                        },
                        new
                        {
                            Id = 9,
                            Calories = 1377,
                            CookedAt = new DateTime(2023, 9, 30, 1, 27, 22, 988, DateTimeKind.Local).AddTicks(3865),
                            Price = 582.256840780057600m
                        },
                        new
                        {
                            Id = 10,
                            Calories = 1493,
                            CookedAt = new DateTime(2023, 9, 30, 9, 18, 23, 228, DateTimeKind.Local).AddTicks(9390),
                            Price = 775.753804057646800m
                        },
                        new
                        {
                            Id = 11,
                            Calories = 834,
                            CookedAt = new DateTime(2023, 9, 30, 3, 36, 24, 319, DateTimeKind.Local).AddTicks(3959),
                            Price = 188.8132459803602500m
                        },
                        new
                        {
                            Id = 12,
                            Calories = 1060,
                            CookedAt = new DateTime(2023, 9, 30, 6, 57, 36, 783, DateTimeKind.Local).AddTicks(8733),
                            Price = 746.841464624907100m
                        },
                        new
                        {
                            Id = 13,
                            Calories = 807,
                            CookedAt = new DateTime(2023, 9, 29, 18, 13, 58, 23, DateTimeKind.Local).AddTicks(8371),
                            Price = 729.569306612098900m
                        },
                        new
                        {
                            Id = 14,
                            Calories = 1747,
                            CookedAt = new DateTime(2023, 9, 29, 17, 10, 14, 588, DateTimeKind.Local).AddTicks(4549),
                            Price = 406.903137319768600m
                        },
                        new
                        {
                            Id = 15,
                            Calories = 800,
                            CookedAt = new DateTime(2023, 9, 30, 4, 6, 27, 772, DateTimeKind.Local).AddTicks(5359),
                            Price = 796.00726089675100m
                        },
                        new
                        {
                            Id = 16,
                            Calories = 1900,
                            CookedAt = new DateTime(2023, 9, 29, 19, 40, 28, 474, DateTimeKind.Local).AddTicks(9117),
                            Price = 470.92753611044200m
                        },
                        new
                        {
                            Id = 17,
                            Calories = 1423,
                            CookedAt = new DateTime(2023, 9, 30, 0, 34, 29, 598, DateTimeKind.Local).AddTicks(9364),
                            Price = 899.208015411003400m
                        },
                        new
                        {
                            Id = 18,
                            Calories = 1628,
                            CookedAt = new DateTime(2023, 9, 30, 10, 50, 57, 962, DateTimeKind.Local).AddTicks(7432),
                            Price = 882.750062809938700m
                        },
                        new
                        {
                            Id = 19,
                            Calories = 1527,
                            CookedAt = new DateTime(2023, 9, 30, 1, 37, 34, 695, DateTimeKind.Local).AddTicks(8813),
                            Price = 906.632639027034400m
                        },
                        new
                        {
                            Id = 20,
                            Calories = 700,
                            CookedAt = new DateTime(2023, 9, 30, 1, 55, 26, 413, DateTimeKind.Local).AddTicks(8618),
                            Price = 516.720764059717600m
                        },
                        new
                        {
                            Id = 21,
                            Calories = 899,
                            CookedAt = new DateTime(2023, 9, 30, 9, 23, 32, 702, DateTimeKind.Local).AddTicks(9894),
                            Price = 588.160744040749600m
                        },
                        new
                        {
                            Id = 22,
                            Calories = 1116,
                            CookedAt = new DateTime(2023, 9, 29, 17, 19, 34, 524, DateTimeKind.Local).AddTicks(286),
                            Price = 564.432286661293600m
                        },
                        new
                        {
                            Id = 23,
                            Calories = 1432,
                            CookedAt = new DateTime(2023, 9, 30, 1, 9, 35, 15, DateTimeKind.Local).AddTicks(4810),
                            Price = 100.204969679064181900m
                        },
                        new
                        {
                            Id = 24,
                            Calories = 1374,
                            CookedAt = new DateTime(2023, 9, 29, 17, 1, 7, 18, DateTimeKind.Local).AddTicks(7816),
                            Price = 899.2367910260200m
                        },
                        new
                        {
                            Id = 25,
                            Calories = 1627,
                            CookedAt = new DateTime(2023, 9, 29, 18, 0, 4, 229, DateTimeKind.Local).AddTicks(5986),
                            Price = 674.071563622260700m
                        },
                        new
                        {
                            Id = 26,
                            Calories = 774,
                            CookedAt = new DateTime(2023, 9, 29, 23, 28, 46, 695, DateTimeKind.Local).AddTicks(637),
                            Price = 717.995160103245400m
                        },
                        new
                        {
                            Id = 27,
                            Calories = 831,
                            CookedAt = new DateTime(2023, 9, 29, 21, 25, 18, 829, DateTimeKind.Local).AddTicks(9622),
                            Price = 870.061210802412400m
                        },
                        new
                        {
                            Id = 28,
                            Calories = 1309,
                            CookedAt = new DateTime(2023, 9, 30, 1, 17, 15, 746, DateTimeKind.Local).AddTicks(6412),
                            Price = 308.117850056807500m
                        },
                        new
                        {
                            Id = 29,
                            Calories = 1714,
                            CookedAt = new DateTime(2023, 9, 30, 7, 55, 21, 610, DateTimeKind.Local).AddTicks(8043),
                            Price = 618.110991145475200m
                        },
                        new
                        {
                            Id = 30,
                            Calories = 1057,
                            CookedAt = new DateTime(2023, 9, 29, 19, 7, 59, 408, DateTimeKind.Local).AddTicks(6537),
                            Price = 399.765973483859500m
                        },
                        new
                        {
                            Id = 31,
                            Calories = 986,
                            CookedAt = new DateTime(2023, 9, 30, 5, 36, 54, 924, DateTimeKind.Local).AddTicks(1022),
                            Price = 526.262420633341600m
                        },
                        new
                        {
                            Id = 32,
                            Calories = 555,
                            CookedAt = new DateTime(2023, 9, 29, 23, 17, 22, 0, DateTimeKind.Local).AddTicks(1393),
                            Price = 570.405541825559800m
                        },
                        new
                        {
                            Id = 33,
                            Calories = 1393,
                            CookedAt = new DateTime(2023, 9, 29, 22, 2, 37, 907, DateTimeKind.Local).AddTicks(8692),
                            Price = 854.492349410047900m
                        },
                        new
                        {
                            Id = 34,
                            Calories = 1458,
                            CookedAt = new DateTime(2023, 9, 30, 3, 38, 16, 591, DateTimeKind.Local).AddTicks(7968),
                            Price = 738.019289782713700m
                        },
                        new
                        {
                            Id = 35,
                            Calories = 1010,
                            CookedAt = new DateTime(2023, 9, 30, 10, 51, 42, 533, DateTimeKind.Local).AddTicks(5313),
                            Price = 524.493908480532700m
                        },
                        new
                        {
                            Id = 36,
                            Calories = 1640,
                            CookedAt = new DateTime(2023, 9, 29, 23, 31, 27, 855, DateTimeKind.Local).AddTicks(1467),
                            Price = 417.781352733745600m
                        },
                        new
                        {
                            Id = 37,
                            Calories = 1381,
                            CookedAt = new DateTime(2023, 9, 30, 5, 51, 0, 109, DateTimeKind.Local).AddTicks(5202),
                            Price = 660.312936005205700m
                        },
                        new
                        {
                            Id = 38,
                            Calories = 1361,
                            CookedAt = new DateTime(2023, 9, 30, 0, 12, 22, 527, DateTimeKind.Local).AddTicks(8736),
                            Price = 318.071476102204900m
                        },
                        new
                        {
                            Id = 39,
                            Calories = 1556,
                            CookedAt = new DateTime(2023, 9, 29, 19, 34, 18, 188, DateTimeKind.Local).AddTicks(98),
                            Price = 767.857517564845600m
                        },
                        new
                        {
                            Id = 40,
                            Calories = 725,
                            CookedAt = new DateTime(2023, 9, 29, 19, 34, 30, 609, DateTimeKind.Local).AddTicks(9259),
                            Price = 171.6801788795594500m
                        },
                        new
                        {
                            Id = 41,
                            Calories = 1103,
                            CookedAt = new DateTime(2023, 9, 30, 10, 24, 18, 667, DateTimeKind.Local).AddTicks(6875),
                            Price = 551.937738889959400m
                        },
                        new
                        {
                            Id = 42,
                            Calories = 1980,
                            CookedAt = new DateTime(2023, 9, 29, 22, 44, 56, 515, DateTimeKind.Local).AddTicks(1055),
                            Price = 808.88626946032300m
                        },
                        new
                        {
                            Id = 43,
                            Calories = 474,
                            CookedAt = new DateTime(2023, 9, 29, 17, 56, 30, 170, DateTimeKind.Local).AddTicks(1495),
                            Price = 768.792659443602400m
                        },
                        new
                        {
                            Id = 44,
                            Calories = 1325,
                            CookedAt = new DateTime(2023, 9, 30, 7, 8, 31, 868, DateTimeKind.Local).AddTicks(6276),
                            Price = 519.247858752054100m
                        },
                        new
                        {
                            Id = 45,
                            Calories = 1384,
                            CookedAt = new DateTime(2023, 9, 30, 11, 51, 45, 730, DateTimeKind.Local).AddTicks(8297),
                            Price = 455.314802963735800m
                        },
                        new
                        {
                            Id = 46,
                            Calories = 1802,
                            CookedAt = new DateTime(2023, 9, 30, 12, 14, 17, 356, DateTimeKind.Local).AddTicks(6611),
                            Price = 773.123293224887500m
                        },
                        new
                        {
                            Id = 47,
                            Calories = 1312,
                            CookedAt = new DateTime(2023, 9, 29, 22, 39, 2, 879, DateTimeKind.Local).AddTicks(2668),
                            Price = 693.342315897394600m
                        },
                        new
                        {
                            Id = 48,
                            Calories = 903,
                            CookedAt = new DateTime(2023, 9, 30, 3, 47, 52, 950, DateTimeKind.Local).AddTicks(4472),
                            Price = 639.563092552811800m
                        },
                        new
                        {
                            Id = 49,
                            Calories = 1153,
                            CookedAt = new DateTime(2023, 9, 29, 21, 48, 0, 736, DateTimeKind.Local).AddTicks(5648),
                            Price = 627.498711119921500m
                        },
                        new
                        {
                            Id = 50,
                            Calories = 1471,
                            CookedAt = new DateTime(2023, 9, 30, 12, 24, 37, 805, DateTimeKind.Local).AddTicks(9927),
                            Price = 721.27553537511100m
                        },
                        new
                        {
                            Id = 51,
                            Calories = 1400,
                            CookedAt = new DateTime(2023, 9, 30, 5, 46, 47, 227, DateTimeKind.Local).AddTicks(2255),
                            Price = 279.505472941703800m
                        },
                        new
                        {
                            Id = 52,
                            Calories = 527,
                            CookedAt = new DateTime(2023, 9, 30, 5, 38, 5, 340, DateTimeKind.Local).AddTicks(8145),
                            Price = 973.644809809176100m
                        },
                        new
                        {
                            Id = 53,
                            Calories = 651,
                            CookedAt = new DateTime(2023, 9, 29, 20, 10, 16, 538, DateTimeKind.Local).AddTicks(9596),
                            Price = 487.610090061608800m
                        },
                        new
                        {
                            Id = 54,
                            Calories = 1785,
                            CookedAt = new DateTime(2023, 9, 30, 0, 20, 18, 637, DateTimeKind.Local).AddTicks(7940),
                            Price = 945.144433625114800m
                        },
                        new
                        {
                            Id = 55,
                            Calories = 790,
                            CookedAt = new DateTime(2023, 9, 30, 8, 36, 41, 605, DateTimeKind.Local).AddTicks(813),
                            Price = 204.483432416842900m
                        },
                        new
                        {
                            Id = 56,
                            Calories = 1667,
                            CookedAt = new DateTime(2023, 9, 30, 6, 59, 11, 533, DateTimeKind.Local).AddTicks(5660),
                            Price = 835.175392340970700m
                        },
                        new
                        {
                            Id = 57,
                            Calories = 1737,
                            CookedAt = new DateTime(2023, 9, 29, 20, 43, 7, 903, DateTimeKind.Local).AddTicks(4909),
                            Price = 626.301421650286300m
                        },
                        new
                        {
                            Id = 58,
                            Calories = 437,
                            CookedAt = new DateTime(2023, 9, 30, 1, 43, 29, 727, DateTimeKind.Local).AddTicks(9662),
                            Price = 913.612944478924900m
                        },
                        new
                        {
                            Id = 59,
                            Calories = 1545,
                            CookedAt = new DateTime(2023, 9, 30, 0, 24, 19, 921, DateTimeKind.Local).AddTicks(7125),
                            Price = 744.68057218544800m
                        },
                        new
                        {
                            Id = 60,
                            Calories = 612,
                            CookedAt = new DateTime(2023, 9, 29, 18, 55, 23, 308, DateTimeKind.Local).AddTicks(4908),
                            Price = 750.443136619922200m
                        },
                        new
                        {
                            Id = 61,
                            Calories = 1509,
                            CookedAt = new DateTime(2023, 9, 30, 8, 55, 21, 470, DateTimeKind.Local).AddTicks(3170),
                            Price = 159.7673538045776800m
                        },
                        new
                        {
                            Id = 62,
                            Calories = 1715,
                            CookedAt = new DateTime(2023, 9, 30, 14, 57, 16, 817, DateTimeKind.Local).AddTicks(6564),
                            Price = 954.007412957148700m
                        },
                        new
                        {
                            Id = 63,
                            Calories = 1442,
                            CookedAt = new DateTime(2023, 9, 30, 13, 15, 20, 852, DateTimeKind.Local).AddTicks(491),
                            Price = 438.904019719985500m
                        },
                        new
                        {
                            Id = 64,
                            Calories = 871,
                            CookedAt = new DateTime(2023, 9, 30, 9, 8, 45, 593, DateTimeKind.Local).AddTicks(769),
                            Price = 634.632874928514100m
                        },
                        new
                        {
                            Id = 65,
                            Calories = 1391,
                            CookedAt = new DateTime(2023, 9, 30, 5, 34, 53, 923, DateTimeKind.Local).AddTicks(1302),
                            Price = 308.516478080902300m
                        },
                        new
                        {
                            Id = 66,
                            Calories = 1686,
                            CookedAt = new DateTime(2023, 9, 30, 6, 50, 5, 179, DateTimeKind.Local).AddTicks(2105),
                            Price = 752.261488151440600m
                        },
                        new
                        {
                            Id = 67,
                            Calories = 1646,
                            CookedAt = new DateTime(2023, 9, 30, 2, 13, 11, 636, DateTimeKind.Local).AddTicks(1281),
                            Price = 703.664984807009200m
                        },
                        new
                        {
                            Id = 68,
                            Calories = 552,
                            CookedAt = new DateTime(2023, 9, 30, 1, 15, 43, 103, DateTimeKind.Local).AddTicks(8661),
                            Price = 657.624915664288300m
                        },
                        new
                        {
                            Id = 69,
                            Calories = 1002,
                            CookedAt = new DateTime(2023, 9, 30, 1, 43, 39, 692, DateTimeKind.Local).AddTicks(5605),
                            Price = 604.078285347516700m
                        },
                        new
                        {
                            Id = 70,
                            Calories = 1783,
                            CookedAt = new DateTime(2023, 9, 30, 4, 33, 6, 647, DateTimeKind.Local).AddTicks(3268),
                            Price = 981.167801215096900m
                        },
                        new
                        {
                            Id = 71,
                            Calories = 1090,
                            CookedAt = new DateTime(2023, 9, 30, 8, 49, 8, 719, DateTimeKind.Local).AddTicks(8371),
                            Price = 917.85814249892500m
                        },
                        new
                        {
                            Id = 72,
                            Calories = 436,
                            CookedAt = new DateTime(2023, 9, 30, 3, 2, 38, 300, DateTimeKind.Local).AddTicks(4214),
                            Price = 664.615565577782200m
                        },
                        new
                        {
                            Id = 73,
                            Calories = 1143,
                            CookedAt = new DateTime(2023, 9, 30, 1, 44, 43, 184, DateTimeKind.Local).AddTicks(9173),
                            Price = 359.565573829890700m
                        },
                        new
                        {
                            Id = 74,
                            Calories = 1367,
                            CookedAt = new DateTime(2023, 9, 30, 10, 50, 38, 170, DateTimeKind.Local).AddTicks(878),
                            Price = 937.365757849377100m
                        },
                        new
                        {
                            Id = 75,
                            Calories = 984,
                            CookedAt = new DateTime(2023, 9, 29, 16, 54, 1, 268, DateTimeKind.Local).AddTicks(4854),
                            Price = 129.3673252272056200m
                        },
                        new
                        {
                            Id = 76,
                            Calories = 1095,
                            CookedAt = new DateTime(2023, 9, 30, 7, 16, 31, 987, DateTimeKind.Local).AddTicks(9209),
                            Price = 848.512067850018100m
                        },
                        new
                        {
                            Id = 77,
                            Calories = 1460,
                            CookedAt = new DateTime(2023, 9, 30, 0, 59, 18, 167, DateTimeKind.Local).AddTicks(1298),
                            Price = 267.220796615777800m
                        },
                        new
                        {
                            Id = 78,
                            Calories = 1436,
                            CookedAt = new DateTime(2023, 9, 30, 3, 55, 3, 252, DateTimeKind.Local).AddTicks(4850),
                            Price = 367.85333886554800m
                        },
                        new
                        {
                            Id = 79,
                            Calories = 1781,
                            CookedAt = new DateTime(2023, 9, 30, 10, 5, 28, 59, DateTimeKind.Local).AddTicks(1068),
                            Price = 879.439745780845300m
                        },
                        new
                        {
                            Id = 80,
                            Calories = 1052,
                            CookedAt = new DateTime(2023, 9, 29, 17, 4, 10, 570, DateTimeKind.Local).AddTicks(2069),
                            Price = 631.87725954026800m
                        },
                        new
                        {
                            Id = 81,
                            Calories = 1456,
                            CookedAt = new DateTime(2023, 9, 30, 1, 41, 7, 633, DateTimeKind.Local).AddTicks(7693),
                            Price = 287.878313340643600m
                        },
                        new
                        {
                            Id = 82,
                            Calories = 1047,
                            CookedAt = new DateTime(2023, 9, 30, 12, 44, 28, 104, DateTimeKind.Local).AddTicks(234),
                            Price = 546.879310699234600m
                        },
                        new
                        {
                            Id = 83,
                            Calories = 1964,
                            CookedAt = new DateTime(2023, 9, 29, 18, 21, 56, 226, DateTimeKind.Local).AddTicks(236),
                            Price = 415.529242940121400m
                        },
                        new
                        {
                            Id = 84,
                            Calories = 413,
                            CookedAt = new DateTime(2023, 9, 29, 21, 53, 34, 80, DateTimeKind.Local).AddTicks(5129),
                            Price = 622.291722028444900m
                        },
                        new
                        {
                            Id = 85,
                            Calories = 442,
                            CookedAt = new DateTime(2023, 9, 30, 10, 28, 54, 559, DateTimeKind.Local).AddTicks(9376),
                            Price = 242.360934133406500m
                        },
                        new
                        {
                            Id = 86,
                            Calories = 612,
                            CookedAt = new DateTime(2023, 9, 30, 5, 5, 9, 878, DateTimeKind.Local).AddTicks(2904),
                            Price = 922.27951486216900m
                        },
                        new
                        {
                            Id = 87,
                            Calories = 1234,
                            CookedAt = new DateTime(2023, 9, 30, 12, 8, 32, 990, DateTimeKind.Local).AddTicks(793),
                            Price = 699.226961393940400m
                        },
                        new
                        {
                            Id = 88,
                            Calories = 1019,
                            CookedAt = new DateTime(2023, 9, 29, 22, 35, 34, 808, DateTimeKind.Local).AddTicks(2475),
                            Price = 914.923227856881700m
                        },
                        new
                        {
                            Id = 89,
                            Calories = 1621,
                            CookedAt = new DateTime(2023, 9, 30, 1, 52, 53, 882, DateTimeKind.Local).AddTicks(9213),
                            Price = 372.161768464834300m
                        },
                        new
                        {
                            Id = 90,
                            Calories = 910,
                            CookedAt = new DateTime(2023, 9, 29, 22, 16, 23, 0, DateTimeKind.Local).AddTicks(9255),
                            Price = 407.926326850998400m
                        },
                        new
                        {
                            Id = 91,
                            Calories = 1056,
                            CookedAt = new DateTime(2023, 9, 30, 9, 31, 15, 726, DateTimeKind.Local).AddTicks(8632),
                            Price = 784.567535932357300m
                        },
                        new
                        {
                            Id = 92,
                            Calories = 1731,
                            CookedAt = new DateTime(2023, 9, 30, 7, 21, 33, 107, DateTimeKind.Local).AddTicks(5314),
                            Price = 427.396386010777300m
                        },
                        new
                        {
                            Id = 93,
                            Calories = 1886,
                            CookedAt = new DateTime(2023, 9, 30, 4, 51, 38, 105, DateTimeKind.Local).AddTicks(7101),
                            Price = 217.958726962240300m
                        },
                        new
                        {
                            Id = 94,
                            Calories = 1758,
                            CookedAt = new DateTime(2023, 9, 30, 6, 19, 54, 457, DateTimeKind.Local).AddTicks(9035),
                            Price = 515.592315457686100m
                        },
                        new
                        {
                            Id = 95,
                            Calories = 1113,
                            CookedAt = new DateTime(2023, 9, 30, 1, 57, 1, 590, DateTimeKind.Local).AddTicks(8923),
                            Price = 878.587168122027100m
                        },
                        new
                        {
                            Id = 96,
                            Calories = 1435,
                            CookedAt = new DateTime(2023, 9, 30, 2, 19, 41, 234, DateTimeKind.Local).AddTicks(4436),
                            Price = 593.251278901904800m
                        },
                        new
                        {
                            Id = 97,
                            Calories = 902,
                            CookedAt = new DateTime(2023, 9, 29, 16, 56, 52, 665, DateTimeKind.Local).AddTicks(8292),
                            Price = 141.0854206232203300m
                        },
                        new
                        {
                            Id = 98,
                            Calories = 1802,
                            CookedAt = new DateTime(2023, 9, 30, 5, 38, 7, 577, DateTimeKind.Local).AddTicks(3105),
                            Price = 342.645082393808800m
                        },
                        new
                        {
                            Id = 99,
                            Calories = 535,
                            CookedAt = new DateTime(2023, 9, 29, 21, 18, 32, 83, DateTimeKind.Local).AddTicks(4105),
                            Price = 619.36029108755200m
                        },
                        new
                        {
                            Id = 100,
                            Calories = 759,
                            CookedAt = new DateTime(2023, 9, 29, 20, 44, 28, 481, DateTimeKind.Local).AddTicks(7841),
                            Price = 828.654350115569500m
                        });
                });

            modelBuilder.Entity("AutoEatery.Data.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ингредиент №1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ингредиент №2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ингредиент №3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ингредиент №4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ингредиент №5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ингредиент №6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ингредиент №7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ингредиент №8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ингредиент №9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ингредиент №10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ингредиент №11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ингредиент №12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ингредиент №13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ингредиент №14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ингредиент №15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ингредиент №16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ингредиент №17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Ингредиент №18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ингредиент №19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ингредиент №20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Ингредиент №21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Ингредиент №22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ингредиент №23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Ингредиент №24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ингредиент №25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Ингредиент №26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Ингредиент №27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Ингредиент №28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Ингредиент №29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Ингредиент №30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Ингредиент №31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Ингредиент №32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Ингредиент №33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Ингредиент №34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Ингредиент №35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Ингредиент №36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Ингредиент №37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Ингредиент №38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ингредиент №39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Ингредиент №40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Ингредиент №41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Ингредиент №42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Ингредиент №43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Ингредиент №44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Ингредиент №45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Ингредиент №46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Ингредиент №47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Ингредиент №48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Ингредиент №49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Ингредиент №50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Ингредиент №51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ингредиент №52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Ингредиент №53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Ингредиент №54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Ингредиент №55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Ингредиент №56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Ингредиент №57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ингредиент №58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Ингредиент №59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Ингредиент №60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Ингредиент №61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Ингредиент №62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Ингредиент №63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Ингредиент №64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Ингредиент №65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ингредиент №66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Ингредиент №67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Ингредиент №68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Ингредиент №69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Ингредиент №70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Ингредиент №71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Ингредиент №72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Ингредиент №73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Ингредиент №74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Ингредиент №75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Ингредиент №76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Ингредиент №77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Ингредиент №78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Ингредиент №79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Ингредиент №80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Ингредиент №81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ингредиент №82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Ингредиент №83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Ингредиент №84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Ингредиент №85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Ингредиент №86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Ингредиент №87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Ингредиент №88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Ингредиент №89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Ингредиент №90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Ингредиент №91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Ингредиент №92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Ингредиент №93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Ингредиент №94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Ингредиент №95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Ингредиент №96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Ингредиент №97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Ингредиент №98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Ингредиент №99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Ингредиент №100"
                        });
                });

            modelBuilder.Entity("AutoEatery.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 5,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 6,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 7,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 8,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 9,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 10,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 11,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 12,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 13,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 14,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 15,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 16,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 17,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 18,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 19,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 20,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 21,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 22,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 23,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 24,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 25,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 26,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 27,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 28,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 29,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 30,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 31,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 32,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 33,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 34,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 35,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 36,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 37,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 38,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 39,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 40,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 41,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 42,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 43,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 44,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 45,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 46,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 47,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 48,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 49,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 50,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 51,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 52,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 53,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 54,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 55,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 56,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 57,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 58,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 59,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 60,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 61,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 62,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 63,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 64,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 65,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 66,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 67,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 68,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 69,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 70,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 71,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 72,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 73,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 74,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 75,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 76,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 77,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 78,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 79,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 80,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 81,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 82,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 83,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 84,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 85,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 86,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 87,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 88,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 89,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 90,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 91,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 92,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 93,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 94,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 95,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 96,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 97,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 98,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 99,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 100,
                            TotalCost = 0m
                        });
                });

            modelBuilder.Entity("AutoEatery.Data.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrganizationName = "Организация №1"
                        },
                        new
                        {
                            Id = 2,
                            OrganizationName = "Организация №2"
                        },
                        new
                        {
                            Id = 3,
                            OrganizationName = "Организация №3"
                        },
                        new
                        {
                            Id = 4,
                            OrganizationName = "Организация №4"
                        },
                        new
                        {
                            Id = 5,
                            OrganizationName = "Организация №5"
                        },
                        new
                        {
                            Id = 6,
                            OrganizationName = "Организация №6"
                        },
                        new
                        {
                            Id = 7,
                            OrganizationName = "Организация №7"
                        },
                        new
                        {
                            Id = 8,
                            OrganizationName = "Организация №8"
                        },
                        new
                        {
                            Id = 9,
                            OrganizationName = "Организация №9"
                        },
                        new
                        {
                            Id = 10,
                            OrganizationName = "Организация №10"
                        },
                        new
                        {
                            Id = 11,
                            OrganizationName = "Организация №11"
                        },
                        new
                        {
                            Id = 12,
                            OrganizationName = "Организация №12"
                        },
                        new
                        {
                            Id = 13,
                            OrganizationName = "Организация №13"
                        },
                        new
                        {
                            Id = 14,
                            OrganizationName = "Организация №14"
                        },
                        new
                        {
                            Id = 15,
                            OrganizationName = "Организация №15"
                        },
                        new
                        {
                            Id = 16,
                            OrganizationName = "Организация №16"
                        },
                        new
                        {
                            Id = 17,
                            OrganizationName = "Организация №17"
                        },
                        new
                        {
                            Id = 18,
                            OrganizationName = "Организация №18"
                        },
                        new
                        {
                            Id = 19,
                            OrganizationName = "Организация №19"
                        },
                        new
                        {
                            Id = 20,
                            OrganizationName = "Организация №20"
                        },
                        new
                        {
                            Id = 21,
                            OrganizationName = "Организация №21"
                        },
                        new
                        {
                            Id = 22,
                            OrganizationName = "Организация №22"
                        },
                        new
                        {
                            Id = 23,
                            OrganizationName = "Организация №23"
                        },
                        new
                        {
                            Id = 24,
                            OrganizationName = "Организация №24"
                        },
                        new
                        {
                            Id = 25,
                            OrganizationName = "Организация №25"
                        },
                        new
                        {
                            Id = 26,
                            OrganizationName = "Организация №26"
                        },
                        new
                        {
                            Id = 27,
                            OrganizationName = "Организация №27"
                        },
                        new
                        {
                            Id = 28,
                            OrganizationName = "Организация №28"
                        },
                        new
                        {
                            Id = 29,
                            OrganizationName = "Организация №29"
                        },
                        new
                        {
                            Id = 30,
                            OrganizationName = "Организация №30"
                        },
                        new
                        {
                            Id = 31,
                            OrganizationName = "Организация №31"
                        },
                        new
                        {
                            Id = 32,
                            OrganizationName = "Организация №32"
                        },
                        new
                        {
                            Id = 33,
                            OrganizationName = "Организация №33"
                        },
                        new
                        {
                            Id = 34,
                            OrganizationName = "Организация №34"
                        },
                        new
                        {
                            Id = 35,
                            OrganizationName = "Организация №35"
                        },
                        new
                        {
                            Id = 36,
                            OrganizationName = "Организация №36"
                        },
                        new
                        {
                            Id = 37,
                            OrganizationName = "Организация №37"
                        },
                        new
                        {
                            Id = 38,
                            OrganizationName = "Организация №38"
                        },
                        new
                        {
                            Id = 39,
                            OrganizationName = "Организация №39"
                        },
                        new
                        {
                            Id = 40,
                            OrganizationName = "Организация №40"
                        },
                        new
                        {
                            Id = 41,
                            OrganizationName = "Организация №41"
                        },
                        new
                        {
                            Id = 42,
                            OrganizationName = "Организация №42"
                        },
                        new
                        {
                            Id = 43,
                            OrganizationName = "Организация №43"
                        },
                        new
                        {
                            Id = 44,
                            OrganizationName = "Организация №44"
                        },
                        new
                        {
                            Id = 45,
                            OrganizationName = "Организация №45"
                        },
                        new
                        {
                            Id = 46,
                            OrganizationName = "Организация №46"
                        },
                        new
                        {
                            Id = 47,
                            OrganizationName = "Организация №47"
                        },
                        new
                        {
                            Id = 48,
                            OrganizationName = "Организация №48"
                        },
                        new
                        {
                            Id = 49,
                            OrganizationName = "Организация №49"
                        },
                        new
                        {
                            Id = 50,
                            OrganizationName = "Организация №50"
                        },
                        new
                        {
                            Id = 51,
                            OrganizationName = "Организация №51"
                        },
                        new
                        {
                            Id = 52,
                            OrganizationName = "Организация №52"
                        },
                        new
                        {
                            Id = 53,
                            OrganizationName = "Организация №53"
                        },
                        new
                        {
                            Id = 54,
                            OrganizationName = "Организация №54"
                        },
                        new
                        {
                            Id = 55,
                            OrganizationName = "Организация №55"
                        },
                        new
                        {
                            Id = 56,
                            OrganizationName = "Организация №56"
                        },
                        new
                        {
                            Id = 57,
                            OrganizationName = "Организация №57"
                        },
                        new
                        {
                            Id = 58,
                            OrganizationName = "Организация №58"
                        },
                        new
                        {
                            Id = 59,
                            OrganizationName = "Организация №59"
                        },
                        new
                        {
                            Id = 60,
                            OrganizationName = "Организация №60"
                        },
                        new
                        {
                            Id = 61,
                            OrganizationName = "Организация №61"
                        },
                        new
                        {
                            Id = 62,
                            OrganizationName = "Организация №62"
                        },
                        new
                        {
                            Id = 63,
                            OrganizationName = "Организация №63"
                        },
                        new
                        {
                            Id = 64,
                            OrganizationName = "Организация №64"
                        },
                        new
                        {
                            Id = 65,
                            OrganizationName = "Организация №65"
                        },
                        new
                        {
                            Id = 66,
                            OrganizationName = "Организация №66"
                        },
                        new
                        {
                            Id = 67,
                            OrganizationName = "Организация №67"
                        },
                        new
                        {
                            Id = 68,
                            OrganizationName = "Организация №68"
                        },
                        new
                        {
                            Id = 69,
                            OrganizationName = "Организация №69"
                        },
                        new
                        {
                            Id = 70,
                            OrganizationName = "Организация №70"
                        },
                        new
                        {
                            Id = 71,
                            OrganizationName = "Организация №71"
                        },
                        new
                        {
                            Id = 72,
                            OrganizationName = "Организация №72"
                        },
                        new
                        {
                            Id = 73,
                            OrganizationName = "Организация №73"
                        },
                        new
                        {
                            Id = 74,
                            OrganizationName = "Организация №74"
                        },
                        new
                        {
                            Id = 75,
                            OrganizationName = "Организация №75"
                        },
                        new
                        {
                            Id = 76,
                            OrganizationName = "Организация №76"
                        },
                        new
                        {
                            Id = 77,
                            OrganizationName = "Организация №77"
                        },
                        new
                        {
                            Id = 78,
                            OrganizationName = "Организация №78"
                        },
                        new
                        {
                            Id = 79,
                            OrganizationName = "Организация №79"
                        },
                        new
                        {
                            Id = 80,
                            OrganizationName = "Организация №80"
                        },
                        new
                        {
                            Id = 81,
                            OrganizationName = "Организация №81"
                        },
                        new
                        {
                            Id = 82,
                            OrganizationName = "Организация №82"
                        },
                        new
                        {
                            Id = 83,
                            OrganizationName = "Организация №83"
                        },
                        new
                        {
                            Id = 84,
                            OrganizationName = "Организация №84"
                        },
                        new
                        {
                            Id = 85,
                            OrganizationName = "Организация №85"
                        },
                        new
                        {
                            Id = 86,
                            OrganizationName = "Организация №86"
                        },
                        new
                        {
                            Id = 87,
                            OrganizationName = "Организация №87"
                        },
                        new
                        {
                            Id = 88,
                            OrganizationName = "Организация №88"
                        },
                        new
                        {
                            Id = 89,
                            OrganizationName = "Организация №89"
                        },
                        new
                        {
                            Id = 90,
                            OrganizationName = "Организация №90"
                        },
                        new
                        {
                            Id = 91,
                            OrganizationName = "Организация №91"
                        },
                        new
                        {
                            Id = 92,
                            OrganizationName = "Организация №92"
                        },
                        new
                        {
                            Id = 93,
                            OrganizationName = "Организация №93"
                        },
                        new
                        {
                            Id = 94,
                            OrganizationName = "Организация №94"
                        },
                        new
                        {
                            Id = 95,
                            OrganizationName = "Организация №95"
                        },
                        new
                        {
                            Id = 96,
                            OrganizationName = "Организация №96"
                        },
                        new
                        {
                            Id = 97,
                            OrganizationName = "Организация №97"
                        },
                        new
                        {
                            Id = 98,
                            OrganizationName = "Организация №98"
                        },
                        new
                        {
                            Id = 99,
                            OrganizationName = "Организация №99"
                        },
                        new
                        {
                            Id = 100,
                            OrganizationName = "Организация №100"
                        });
                });

            modelBuilder.Entity("AutoEatery.Data.Models.Dish", b =>
                {
                    b.HasOne("AutoEatery.Data.Models.Order", null)
                        .WithMany("Dishes")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("AutoEatery.Data.Models.Ingredient", b =>
                {
                    b.HasOne("AutoEatery.Data.Models.Supplier", null)
                        .WithMany("SuppliedIngredients")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("AutoEatery.Data.Models.Order", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("AutoEatery.Data.Models.Supplier", b =>
                {
                    b.Navigation("SuppliedIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
